query TaxRates {
  taxRates(options: { sort: { name: ASC } }) {
    items {
      name
      value
      enabled
      category {
          name
      }
      zone {
          name
      }
    }
  }
}
